name: using
description: Upgrade your class with automatic cleanup and finalization, similar to "using + IDisposable" in C# and "try-with-resource + AutoCloseable" in Java.
version: 1.0.5
repository: https://github.com/d-markey/using

environment:
  sdk: ^3.0.0

dependencies:
  meta: ^1.10.0

dev_dependencies:
  lints:
  test:

topics:
  - resource-management
  - disposable
  - dispose
  - using
